### ISSUE TITLE
Example sites?

### ISSUE THREAD

**Issue by sje30** [tummychow/lanyon-hugo#11]
hi,
do you have any example sites to showcase your nice theme?  I see that there is one on http://themes.gohugo.io/theme/lanyon/ but that looks broken or incomplete (e.g. there is no menu?).

**Comment by tummychow** [comment]
official example: http://lanyon.getpoole.com/
my version: http://tummychow.github.io/lanyon-hugo/ (it looks practically the same)

I agree that the themes.gohugo.io page seems broken. Unfortunately I don't own that page so I can't fix it mysefl. My dev console tells me that it's looking for a livereload dependency on port 1313. Maybe it's being served by `hugo --watch`? (which seems like a bad idea in prod...) You might have to open an issue on hugo or ask around in their forum.

**Comment by tummychow** [comment]
Addendum: I realized after you opened this issue that it had actually been a while since I rebuilt the example pages for this repo (esp considering the recent pagination contribution by nithinphilips), so I went and did that just now. However you still won't see much difference between the official example and mine, because we're both still using very old versions of the lanyon CSS. See #12.

**Comment by sje30** [comment]
Thanks for your help; just sent an issue:

https://github.com/spf13/hugoThemes/issues/97
