### ISSUE TITLE
Looks like broken

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tummychow/lanyon-hugo#20]
![screen shot 2018-04-09 at 6 06 15 pm](https://user-images.githubusercontent.com/3514015/38505786-b617a56e-3c20-11e8-985f-bb50252dd3d8.png)

**Comment by tummychow** [comment]
I'm going to need more details than just a screenshot. What else is in the repo you're building with? How are you serving the files (github pages?)?

**Comment by vitaly-zdanevich** [comment]
I cloned this repo into `themes` and run `hugo server`.

I tried again with some posts:
![image](https://user-images.githubusercontent.com/3514015/38551827-dd59b336-3cc2-11e8-8b9b-9a563d051abb.png)

Hugo `v0.38.1` on Mac.

No problems with another theme - https://github.com/halogenica/beautifulhugo

**Comment by vitaly-zdanevich** [comment]
![image](https://user-images.githubusercontent.com/3514015/38719239-827a7bc4-3ef9-11e8-9717-2d0af53f50a7.png)

**Comment by tummychow** [comment]
uhhh... hm. So that explains the problem (CSS has the wrong mime type), but I can't really imagine _why_ the CSS has the wrong mime type. It's just a static file, there's nothing the theme can do to control what that mime type is.

You mentioned that a different theme was working fine. I notice that [some of the CSS in that theme is custom, but the rest is served from a CDN](https://github.com/halogenica/beautifulhugo/blob/5ab83c3282b766fce61d547d9bb6f7d5eeaab6da/layouts/partials/head.html#L46). The CDN-loaded CSS would certainly not have a mime type issue. Could you repeat this process there and see if you also see mime type errors (specifically on the ones that are not coming from the CDN)? If so, then that indicates some kind of bug in how hugo is serving the files. If not, I might be at a loss.

**Comment by vitaly-zdanevich** [comment]
Another theme still works, also I tried to open index.html locally:
![image](https://user-images.githubusercontent.com/3514015/38719670-cb2bf044-3efb-11e8-87cb-29940162b414.png)
Now it looks like incorrect path.

With `hugo server` the same errors about MIME type.

In Firefox just 404:
![image](https://user-images.githubusercontent.com/3514015/38719780-68f6b66a-3efc-11e8-9bf0-36f799ad322a.png)

The same 404 in Safari:
![image](https://user-images.githubusercontent.com/3514015/38719816-8e9ddf38-3efc-11e8-90fb-1780b7af3553.png)

**Comment by tummychow** [comment]
the path issues when opening locally are irrelevant to this issue. This theme uses relative paths and those won't work for `file://`.

This is what I get when I open hugo server:
![maim-2018-04-12-23 36 23](https://user-images.githubusercontent.com/4285049/38720246-5a26034a-3eaa-11e8-839e-422d8cecb9e4.png)
Notice the response header contains `Content-Type: text/css`. Can you show me a screenshot of the same thing in your setup? I want to see what the actual header value is.

**Comment by vitaly-zdanevich** [comment]
![image](https://user-images.githubusercontent.com/3514015/38750055-62fd6ac8-3f5c-11e8-9ae5-212a8593f460.png)

**Comment by tummychow** [comment]
and if I understand correctly, all of this is with lanyon-hugo cloned under the `themes` folder of your repo? Can you try running `hugo server` in the root of this repository itself? Do you still get `Content-Type: text/plain`?

(Speaking of which, if your repository is public somewhere, please send me a link to it - the debugging becomes a _lot_ easier if I can see exactly what your content and directory layout are.)

**Comment by vitaly-zdanevich** [comment]
`hugo server` from `themes/lanyon-hugo` - I see correct theme, for the first time. Content type for `poole.css` is `text/css`.

Also I tried `hugo` for build - and after that in `public/css` I see `poole.css` and two others files.

[my-blog.zip](https://github.com/tummychow/lanyon-hugo/files/1910149/archive.zip)

**Comment by tummychow** [comment]
okay I figured out what the issue is, and to be honest I probably should have figured it out sooner - it's a path issue. My recommendation would be:

- add `relativeURLs = true` to your config.toml
- you have a few links to images, eg `/blog/img/girl-headphones-back.jpg`. If you take the `/blog` prefix off, then the `relativeURLs` option will fix it for you.
